#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# vim:set shiftwidth=4 tabstop=4 expandtab textwidth=79:
# =============================================================================
# Zach Braff Quotes
# Copyright (C) 2008,2010 Zach "theY4Kman" Kanzler
# Quotes tuple extracted by Jacob Smith
# =============================================================================
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License, version 3.0, as published by the
# Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

from random import randint

import supybot.utils as utils
from supybot.commands import *
import supybot.plugins as plugins
import supybot.ircutils as ircutils
import supybot.callbacks as callbacks

quotes = ("I remember once I went to go see a movie, and in front of me in line there was a little boy who looked so eager to see it, like it was Christmas morning. When he got to the ticket booth it turned out there was only one ticket left; the manager was there and wanted to give it to me instead since I was famous. That's when I knew I'd hit it big. - Zach Braff on fame",
"I mean, they lost both parents. That's just careless. - Zach Braff on orphans",
"It's not that I think the Nazis were right, or anything. It's just that, we weren't there, we don't know. - Zach Braff on the holocaust",
"I mean, I'm a writer, actor, AND director. Not to rock the boat or anything, but compare that to a carpenter and, in the end, who is the better man? - Zach Braff on Jesus",
"I was mad when I heard The Amazing Race wasn't about white people. - Zach Braff on reality shows.",
"Well, at least I'm ok. - Zach Braff on 9/11",
"I'm not being insensitive, but maybe Steve Irwin started it. Not like he can say otherwise now. - Zach Braff on Steve Irwin",
"I wouldn't say I'm bigger than Jesus. If I had to guess, I'd say probably, yeah, but as far as I know, the bible is never clear on this. - Zach Braff on the size of his penis",
"No, I'm not sorry. If a hooker has to die for me to get an erection, then, shit, a hooker has to die. - Zach Braff on dating and relationships",
"I could sell out Madison Square Garden masturbating. - Zach Braff on his fame.",
"I think slavery was an awful, awful period in our history, but when I look at what's become of black culture since emancipation, I think you have to admit, maybe the Confederacy was on to something - Zach Braff",
"If God wanted women to be treated equally to men, he'd have given them penises. - Zach Braff on Women",
"I really don't know why we need a whole month dedicated to blacks. It's not like they're the only ones that suffered. I mean, what about us whites? We're the ones that have to deal with these monkeys everyday, but you don't see us demanding a whole month to ourselves. - Zach Braff on Black history month",
"But I'm alive. - Zach Braff on Friedrich Nietzsche",
"For me, acting in scenes with other people is like playing soccer with a bunch of legless five year olds. It's not really fair to them, but what else can I do, you know? - Zach Braff on co-stars",
"Finding out that McGinley's kid is a retard. - Zach Braff on his favorite Christmas gift",
"Is 'Garden State' the next 'Citizen Kane'? Of course not. I'd like to think we aimed a little higher than that, frankly. - Zach Braff",
"I never go looking for child pornography, but I mean, if somebody sends me an email with some pictures, I'm not going to turn around and report them. - Zach Braff on pedophilia",
"That Hugh Laurie show is nothing but Scrubs fan fiction. - Zach Braff on House",
"I love queers as much as the next guy, I just don't think I should have to sit beside them on public transport. - Zach Braff on Homosexuals",
"My tears cure cancer too, it's just that I laugh at cancer patients. - Zach Braff on Chuck Norris",
"Gay men in L.A. are all a bunch of tens looking for an eleven. - Zach Braff",
"I'm not the kind of person who digs through things other people have thrown away. - Zach Braff on adoption",
"The thing about all these charities is that who sees where the money goes? I don't and you don't. For all I know, the president of Make a Wish just used all the money to buy himself a mansion and a yacht. That's why I keep all of my money for myself, at least then I know I'm doing good for at least one person for sure. - Zach Braff",
"I mean, some people accuse me of being racist. I'm totally not, I'm just better than everybody else. - Zach Braff on Racism",
"Don't get me wrong, I love the idea of killing unwanted babies, it's just that the idea of letting women make a decision doesn't sit well with me. - Zach Braff on abortion.",
"Well, I've thought about donating, but they get so many damn donations already. I read about one foundation that raised over 100 million dollars. Well where the hell did that go? For all I know every starving child has a 2 story house by now. Or maybe they're all raging alcoholics, like homeless people. Homeless people who are more effective when it comes to raising money. Who wants to support alcoholic children? Not me. - Zach Braff on starving children in Africa",
"You always see actors complaining about being typecast and ruining their career. Really, I don't see the point in complaining. If the only role you can play well is a black dude, you're never going to get ahead in this town, and you should just accept it. - Zach Braff on Affirmative Action",
"I had to teach them a lesson. No Scrubs? I don't think so. Let's see them talk bad about my show with only two people singing. - Zach Braff on TLC",
"Being around blind people is always a little frustrating to me because I know they have no idea how handsome I am.  - Zach Braff on disabilities",
"They're really great. I've had a lot of costars, but those two are really phenominal. - Zach Braff on his testicles",
"I feel really bad for everyone who died on 9/11. Not just the people in the World Trade Center, Pentagon, or Flight 93, but all of the terrorists, too. 'Garden State' came out in 2004. That means none of them got a chance to see it. Let that sink in for a second. No wonder they're building a memorial.  - Zach Braff",
"The biggest problem I had with starring in Scrubs were the black doctors. I just had to keep telling myself this show was satire. - Zach Braff on acting challenges",
"I stand stark naked in front of the mirror and gaze directly into my own eyes. I utter 'Good morning, handsome' and my lips quiver as I stare at myown body. I don't break eye contact until I blow my load. Not once do I actually touch myself. - Zach Braff on how he starts his day",
"You always see black people complaining about this and that, but you never see me complaining about how slow they work on my plantation. - Zach Braff",
"Well it's not that I HATE them, but honestly if I saw two homeless people begging for money, one white and one black, and I only had one quarter... Well I'd probably keep it actually. - Zach Braff on African Americans",
"I think a big part of being a success is confidence. Just look at me, I know I'm successful, and I am. - Zach Braff",
"Am I really gonna deny someone the opportunity of a lifetime just because they met me 5 easters early? - Zach Braff on The Age of Consent",
"My first girlfriend would always whine about how her mom was an uncaring alcoholic, her dad left when she was just a little girl, and how her brother died in a car crash or something. But, it's like, she got to date me, you know? So I think that more than makes up for all of those things. - Zach Braff on young love",
"I mean, I understand that because they're disadvantaged that they deserve their own parking spots, but do they have to make them so wide? I never understood how these people were allowed to drive cars but they get these really neat chairs with wheels and they're still not happy, so instead of parking their wheelchairs in the designated spots, they upstage us normal people and get the best parking spots with vehicles that are clearly too sophisticated for them to be handling. Still, you should smile at a cripple, because it's the only bit of happiness they'll ever have. - Zach Braff on handicapped parking",
"I love signing autographs! Sometimes, when people ask me for one, I keep the photo for myself and frame it. It's a Win-Win situation really; I get an extra 25 dollars in my pocket AND another portrait for my bedroom. - Zach Braff",
"A kid came up to me the other day and said, 'Hey, you're the guy on Scrubs!'. Kid, I am Scrubs, and don't you forget it. - Zach Braff on meeting fans.",
"Oh I love children, but I could never eat a whole one. - Zach Braff",
"As an actor, and a writer, and a director, I know how hard it is to plan things out. This sort of thing, it's just... you've really got to respect the effort they put in, you know? - Zach Braff on the Darfur Genocides",
"Retarded kids are the best. When they ask for an autograph I just fake sign a picture and tell them that it's in invisible ink and it will show up later. They totally buy it. It saves me a fortune in markers. - Zach Braff",
"I don't think that other races are inferior, I just think that there's something special about white people. Sometimes, when I think about all the things white people have accomplished throughout history, I smile, and I nod, and I think to myself, 'Yeah, I'm glad I'm on that team.' - Zach Braff",
"I thought the dollar menu solved that? - Zach Braff on world hunger",
"I mean, personally, I would have had no problem surviving. Come on, how hard is it to swim? - Zach Braff on Hurricane Katrina",
"Honestly, do we really need to be concerned with these people? They're dirty, uncivilized, and, correct me if I'm wrong, but I don't think they even get Scrubs over there. - Zach Braff on third world countries",
"Take a dash of Clooney, a pinch of DeNiro, a smidge of Nicholson, and add talent. - Zach Braff on How to make Zach Braff",
"Every time I see a child walking down the street I like to trip them. While they look for their missing teeth, I personally remind them that no matter how hard they try I will always be better than them. - Zach Braff",
"A lot of people consider 9/11 to be a tragedy, and in some ways it is, but I think there's also opportunity for a lot of humor there. - Zach Braff on his upcoming romantic comedy Trade Off",
"Working on 'Scrubs' made me feel guilty because I realized that if I had decided to become an actual doctor, instead of just playing one, I could probably have found a cure to cancer within five years. - Zach Braff",
"I was absolutely devastated when it happened. At first I was speechless, then I just broke down crying. I couldn't eat for a day. The whole time I was just wondering if America would ever be the same after such a tragedy, and even now, I don't think we'll ever fully recover. - Zach Braff on Garden State not winning an Oscar",
"For the first three years, I didn't even bother learning his name. I just yelled, 'Yo, black dude,' whenever I needed him to bring me something to drink or whatever. - Zach Braff on co-star Donald Faison",
"JENGA! - Zach Braff on 9/11",
"The whole situation was a complete misunderstanding. I honestly thought it was an ashtray. Then when I smelled that familiar aroma burning money, then I knew... - Zach Braff on the Salvation Army donation collection buckets",
"I mean, really. They lived on islands, I don't know why they acted all shocked and torn up about it. They should've known better. Or at least should have taken swimming lessons to prevent drowning.  - Zach Braff on the Tsunamis",
"Mine? No, it stays in the kitchen. - Zach Braff on women",
"Sometimes, I stand on my balcony and look at the ants scattered under me twelve floors below on the sidewalk. I stop to think about how my death would impact their lives, and that alone is enough for me to gain the willpower to live another day. An entertainer is a person who must suffer a lot to achieve complete mastery of his own trade. At the end of the day, doctors, lawyers, police officers, firefighters... they come home to a nice family and all, but an entertainer doesn't get that privilege. To answer your question, I have thought about suicide, but I have never brought myself to it because of my self-imposed title of pierrot to the world. - Zach Braff on suicide",
"Yeah, the gay pride movement is precious and all, but I think it's about time we asked ourselves what gay people really have to offer to society. - Zach Braff on homosexuality",
"I'm not saying I did, and I'm not saying I didn't, but I can tell you that she wanted it badly.  But then again, who doesn't want it from Zach Braff. - Zach Braff on impregnating Jamie Lynn Spears",
"I'm pretty sure Africa was made up by the media to scare people. I mean, I've never seen it. Have you? I didn't think so. - Zach Braff on Africa",
"Y'know, they always ask how many licks it takes to get to the center, and I think I might be the only one who's ever actually tried. - Zach Braff on 12 year old girls",
"I don't get why arabs are so pissed off at us. I mean they have enough oil for all of them to drive a hummer at what, maybe 1.50 a gallon? - Zach Braff on the Middle East",
"He wasn't very good at basketball. The final score was 33-0, but I imagine it was the best day of that kid's life. - Zach Braff on his volunteering with children with leukemia",
"Yeah, I have to admit it was pretty big, but I didn't feel threatened by its success at all. I just look at it and think, I could've done a better job I honestly don't see why everyone's still talking about it. - Zach Braff on Hurricane Katrina",
"The greatest trick the Devil ever pulled was convincing the world there's better actors than me. - Zach Braff on Christianity.",
"That's a really harsh word. Let's just say when she woke up, she was surprised to be having sex, okay? - Zach Braff on charges of rape that have been brought against him",
"They speak in clicks and clacks. Do you really think they deserve freedom? - Zach Braff on africans",
"Yeah, I've banged some female costars.  I swore I'd never tell their names, so instead I'll present some anagrams: Sahar Clahke and Haether Gharam. - Zach Braff",
"I knew I'd made it big as an actor when he was shaking just being in my presence. - Zach Braff on Michael J. Fox",
"I like to think of myself as the Chris Benoit of the movie industry, capable of taking any picture and carrying it to box-office success. Take Garden State, without me that would have just been two hours of Portman bitching. - Zach Braff on suicide awareness",
"First I took a shit on the hooker's chest, then I told her I'd pay her a thousand dollars to eat it. She was addicted to crack, so of course she did it. It was so gross, though, it made her throw up, so I said I'd pay her another thousand to lick all that up, too. She started to, but for some reason she started crying as she was doing it, saying, 'I went to college! I have a degree!' Oh man, it was hilarious. I don't know if it was technically sex because I just beat off on her face, but definitely one of my most intense orgasms. - Zach Braff on the best sex of his life",
"I mean, I understand that Scrubs was my big break, but sooner or later you have to move on. I've already directed a movie, which received very good reviews, so it just seems much more important to me now. I feel that in order to better foster my creativity as an actor and director at this point, I need to be surrounded by other talented, artistic individuals, instead of just goofy comedians. - Zach Braff",
"One time a pipe in my sink burst so I can relate to what they're going through - Zach Braff on Hurricane",
"Yeah i saw An Inconvenient Truth, and i dont want to say it was preachy but let's not kid ourselves, i've got far more important work to do - Zach Braff on Global Warming",
"I'm a busy guy; I just get a lot of people that sound like me to go out and visit them.  They don't know the difference and, let's face it, they aren't going to be paying to see my movies  anytime soon. - Zach Braff on visiting blind children",
"I figure it this way - if a woman claims she didn't want me to fuck her, then you already know she's a liar. So what the hell's the point of a trial, y'know? - Zach Braff on rape",
"Whenever I'm feeling a bit down, I always visit the local children's hospital. Knowing that those cancer-kids wont be able to live long enough to surpass me in fame just warms my heart, you know? - Zach Braff on happiness",
"Honestly, I don't see what the big deal is. I mean, she wrote a book, big whoop. Let's see her write, direct, and star in a major motion picture, and THEN maybe I'll have some respect for her - Zach Braff on Hellen Keller",
"To give is better to recieve. - Zach Braff on AIDS",
"Listen, it works in theory. I mean, that's a lot more than we can say for Democracy. - Zach Braff on Communism",
"One thing a lot of people don't know is that they originally offered me the role of Neville Flynn in Snakes on a Plane. I was going to take it, but then I thought to myself, Samuel needs this more than you do, Zach, and I gave the role to him. It's the little things like that that make a difference in the lives of those around you. - Zach Braff",
"I like to drop in on people who picked on me in high school or whatever, just out of the blue, and chat with them to see how they think of me now that I'm a big star. Usually they're a lot nicer. After about half an hour, I excuse myself to go to the bathroom, and leave a few DVDs or pictures there. Then when I come out, I say good-bye and leave. Then I call the cops. - Zach Braff on getting his enemies arrested for possession of child pornography",
"Slavery got shit done. - Zach Braff",
"Women have the right to choose what do with their own bodies. They can take it in the cooch or in the pooper. But that's where their right to choose stops, in my opinion. - Zach Braff on abortion",
"I love the holiday season, almost as much as I love touching myself in front of orphans. - Zach Braff on the holidays.",
"Dude, writing, acting and directing are such easy jobs.  But to do them all as awesomely as Zach Braff does, well that... that's something. - Zach Braff on Zach Braff",
"Don't get me started on cold toilet seats. - Zach Braff on cold toilet seats",
"It blows my mind that there are people out there who deny the holocaust. Why would you ever deny such a great achievement. It's like denying the cure for polio or something. - Zach Braff",
"You know how they do that effect in movies, where they make it look like you have a twin, but it's really just the same actor playing both characters in the scene? I knew this would be the best route, but I just wasn't comfortable dressing as a woman, so I had to hire other actors. - Zach Braff on Garden State",
"It's not that I wanna hurt them or anything,I just really think they make great bar stools - Zach Braff on midgets",
"If a benevolent God exists, so does reincarnation. He wouldn't send me here just once. - Zach Braff on religion",
"I try not to criticize him too much because I always end up comparing his decisions to the ones I would make, and that's really not fair to him. - Zach Braff on George W. Bush",
"I don't have anything against this Jesus guy, but has he written, directed, and starred in his own movie? - Zach Braff on Jesus Christ",
"I mean, I know thousands of people died and everything, but if it happened today, there's just no excuse. They'd be much safer inside a movie theater watching one of my movies instead of burning alive in a collapsing skyscraper. - Zach Braff on 9/11",
"I did theater for a few years while I was in New York, but it was tough having to perform scripts worse than what I knew I could write. - Zach Braff",
"Frankly, I don't blame those poor people, they risk everything they have just to be near me, that is a very worthy effort, and we should help them anyway we can - Zach Braff on illegal inmigration",
"It's not like I didn't know he was twelve years old when I hit him, I just thought he was spraypainting my Porsche. MY Porsche. I mean, which would be more important to you, some punkass twelve year old kid or Zach Braff's Porsche? - Zach Braff on getting Punkd",
"He really wrote all of the parts with me in mind. - Zach Braff on Shakespeare",
"A lot of people say that they piss excellence and shit greatness, but in my case it's true. - Zach Braff on being great",
"I choke them until they spit it out. I can't just have them walking out the door with 10,000 potential baby Half-Braff's in their gullet.  - Zach Braff on blowjobs",
"It doesn't bother me that my films don't win awards. Besides, who is this Oscar asshole anyways. What's important is that they win the Zach Braff. It's a small golden statue of myself that I put on my shelf whenever I make a movie. - Zach Braff on awards",
"People compared Garden State to the Graduate, but when was the last time you saw Dustin Hoffman doing what I do? - Zach Braff on comparisons",
"I'm not actually an arrogant guy. It's just that, truthfully, nobody else can really compare to me.  - Zach Braff on himself",
"I like the punch beggers and panhandlers when they ask me for change. I feel like I am doing my part to clean up the streets. - Zach Braff",
"I don't what his deal is. Maybe it's because I ACTUALLY thought he was a studio janitor or whatever. He should have aimed higher in life. Playing a janitor on TV is just as bad as being one. - Zach Braff on Neil Flynn",
"I know they say that Kurt Cobain killed himself becasue he was a genius, but can you imagine how long he would have lasted if he had written Garden State? I mean, that would be like an instant death penalty for him - Zach Braff on Suicide",
"He is without doubt one of the greatest actors, writers, and directors of our time. He's truly a gift to this Earth and a god amongst us. - Zach Braff on Zach Braff",
"I've turned down a lot of proposed scripts for Scrubs episodes, mainly ones with AIDs patients. It sickens me, really. If you don't want AIDs, don't be a faggot. Or African. I'm neither and I'm fine. - Zach Braff on writers",
"Its not that I'm in love with myself, I'm just trying to pick up everyone else's slack. - Zach Braff",
"Seriously, when's the last time you saw me wear shorts? - Zach Braff on his penis size",
"I was stuck in traffic one day and just kinda thought it would be funny to masturbate. It was sunny and clear out, so I was worried one of the other drivers would see me, but my jeep is pretty high off the ground, so I think no one noticed. I busted a nut and aimed it down, ruining my tweety bird floor mat. I felt kinda stupid after and my mom kept silent the rest of the drive home. It was awkward and I regret it. - Zach Braff on awkward times in his life",
"Frankly, I'm offended. I pay good money for it and these women get it for free without even asking? And then complain about it? It's things like these that make me give up hope on the world - Zach Braff on rape",
"It's not like we are close or anything, we just chat once in a while when our dogs are fighting - Zach Braff on Michael Vick",
"Sure I've had sex with them, but let me give you a word of advise: make sure they're fresh. - Zach Braff on Dead People",
"Yeah i thought about making the character of JD gay... But then i thought, but what about all the poor girls dreams you'll be crushing - Zach Braff on Character development",
"Well, I don't know about this whole situation. I mean, it's nice and all that someone made such a dedicated interactive version of my life, but, I mean, c'mon, where's the Zach's cut of the pie, ya know? - Zach Braff on Grand Theft Auto",
"When I was told they wanted the show to be about doctors, I was a bit reluctant to sign on, you know? I thought, why have a show about doctors when we could have a show about the real heroes, you know, like me? - Zach Braff on the creation of Scrubs",
"It was at that moment I realized that yes, I could have my cake and eat it too. - Zach Braff on the Olsen twins",
"I was originally set to star in 'The Bourne Identity,' but I found it too difficult to even pretend to forget who I was. - Zach Braff",
"I had a dream once. I wanted to do a line of cocaine off a hooker's ass. That's when I realized, 'Hey, I'm freakin' Zach Braff.' I did it the next morning. - Zach Braff on being 5 years old",
"Freud's analysis of the human mind is the only one that makes sense. I am convinced that everyone's problems are rooted in their urges to have sex with me.  - Zach Braff on psychology",
"Personally, I thought it was hilarious. - Zach Braff on Hurricane Katrina",
"I use the N word almost daily. It reminds me that I'm successful - Zach Braff on Success",
"In a perfect world, everybody would be gay.  I mean if everybody looked like Zach Braff, you just wouldn't be able to resist. - Zach Braff on gays",
"Why are there charities for them anyway? I mean, they jump out of aeroplanes. Sure, the landing's a bit rough but it's an exciting life, and hilarious to watch too. - Zach Braff on Paraplegics",
"It really is fascinating stuff, and I've picked it up on Scrubs.  Memorizing lines is at least as hard as studying a text book, I mean, by this point I know about as much as most 'real' doctors. - Zach Braff on modern medicine",
"I pick the songs for my movies by typing a random word - say bee - and then by typing the word pitchfork along with it and then whatever pitchfork album review Google brings up I then look at the album, select the fourth song off of it, and then try t write a film scene around whatever song it is. It's brought only gold so far! - Zach Braff on selecting songs for films",
"My favorite movie moment? When they shoot Old Yeller. Gets me every time. I can never stop laughing at that. - Zach Braff on movies",
"Everyday I question myself. I look in the mirror, or read one of my scripts, or I reflect on my acting and I say to myself 'that was good...but was it Zach Braff good?' Lets just say things have been looking pretty Zach Braff so far. - Zach Braff on motivation",
"Ya know, Hitler was this evil, evil man. But with the World Bank and Israel manipulating America, he might have been on to something... - Zach Braff on Hitler",
"So I was at the gas station the other day, and I saw that there was braille on the pumps. I don't see how they can cater to blind drivers. I mean, there are certain rights you should lose once you lose what makes you a person. - Zach Braff on blind people",
"I mean, yeah for minorities right?  Thinning the herd and such? - Zach Braff on condoms",
"I know the Bible isn't real because it never once mentions me. - Zach Braff",
"Of course killing people is 'wrong', but I think history shows that sometimes it serves the greater good. - Zach Braff on genocide",
"Some guy came up to me the other day and told me he loved me in Scrubs. Does he even know I've been in other things? Asshole.  - Zach Braff on fans",
"I mean it's just crazy. What makes them think they have the privilege to even talk to me? - Zach Braff on B-list celebrities",
"I mean, what's eleven million people now days? - Zach Braff on the Holocaust",
"I've always wanted to have kids of my own, it's just tough finding a woman I wouldn't be wasting my DNA on.  - Zach Braff",
"I never taught a blind/deaf chick to read, but somehow I've managed to turn Scrubs into a watchable show. That may not sound like much, but take a look at my surrounding cast and ask yourself, who's the real miracle worker? - Zach Braff on Anne Sullivan",
"I don't like the idea of drama schools. They only perpetuate the myth that everyone can do what I do - Zach Braff on acting colleges",
"It's really hard to find parts that challenge me as an actor these days. At this point in my career, I feel like I can just sleepwalk through most of my roles and still do a better job than 90 percent of the actors out there. - Zach Braff on acting",
"To say I live a cursed life is an understatement. I have to get up every day and work with people who are not as successful as me nor will they ever be as successful as me. Nobody knows the struggles I go through. - Zach Braff on Scrubs",
"He's really unprofessional. To be honest, I can't wait to finish filming the last season of Scrubs. One time I remember in particular, he came to a shoot at 2:15 in the afternoon complaining about a car accident or something. He didn't remember any of his lines, we wasted an entire day. I'll never work with him again. - Zach Braff on Barack Obama",
"A lot of people look at me, and they wonder 'Is that guy packing some serious heat down there?' Let's just say I have a pretty big dick. - Zach Braff on fame",
"Back in college, I had a friend whose sister got raped. It was sad, I guess, for a while, but I mean, we all got over it and frankly, I was just sick of hearing about it. Everything she said, 'rape, rape, rape,' it was getting pretty old. I stopped talking to the guy soon after... fuck him, you know? He'd always say, 'bros before hos,' but... God, what a hypocrite, huh? - Zach Braff on teen pregnancy",
"I understand why they're yellow, he only had a yellow marker, and then he wanted to be consistent.  But that doesn't explain why some of the characters are black. - Zach Braff on The Simpsons",
"It's always weird being the only white person in a group. It feels like everyone's looking to me for guidance. - Zach Braff on leadership",
"Might as well let them, I mean, there can only be one Zach Braff. Everything else is just downhill. - Zach Braff on abortions",
"Sometimes, I go to Barnes & Noble with the sole intention of moving all copies of the bible to the fiction section. - Zach Braff on religion",
"I don't see why the WGA gets mad. It's not like they have a shortage of those signs.  - Zach Braff on WGA strike signs",
"Compared to my talents, Whoopi Goldberg is like one of those fake plastic Buddhas you get at dollar stores. I mean really, I fail to see the humor in an overweight negro woman with dreadlocks, no eyebrows, and is named after a childish term for flatulence.  - Zach Braff on Whoopi Goldberg",
"I'd really like to give back to the world, but everything I've achieved, I've earned on my own, so what's the point? - Zach Braff on charity",
"Most people just aren't grateful for the lives they have, and it really saddens me. For instance, I said 'hello' to a man the other day, and he didn't even recognize me. It just really saddens me. - Zach Braff on homeless people",
"Don't get me wrong.  They're phenomenal.  But when you reach a point at which you can think faster than them, then you just don't get as excited about them. - Zach Braff on computers",
"I'd like to think that my scripts are more significant than maybe the Bible or the book that the Jews use, whatever it's called. And that's only when I'm having an off day. - Zach Braff",
"I'm not saying eating babies should be legal, but when they're so delicious, what's the harm in it? I don't know what tastes better, their innocence or their gooey rib butter. - Zach Braff",
"Dude, don't bring him near me. I don't care if he's five, I'm gonna punch him. - Zach Braff on Punk'd",
"I personally think it's respectable that they do what they love, despite all opposition. - Zach Braff on rape",
"Was she really that great? Sure, maybe she helped a few homeless people here and there, but I'm on national TV. Who is the more important person? Let America decide. - Zach Braff on Mother Theresa",
"It's an invention against God. - Zach Braff on the wheelchair",
"I'm not gay, but I'm still the kind of guy where,  even though you have no chance, they still want to hang around me so you can get a good mental image and jerk off to me later. - Zach Braff on Homosexuals",
"People always tell me I should run for president, but I don't think they'd give me enough time off to make my films.  - Zach Braff",
"I could see why someone would want to make a website about me, and my quotes. They are all gold. How many people have written, directed AND starred in their own movies. I just don't know why they would want to put words into my mouth, I mean I did write, direct AND star in a critically acclaimed movie. - Zach Braff on http://www.qtex.org/braff/",
"I mean the first time I had it I knew right off the bat it wasn't legit. I think most people are fooled, but I guess when it comes down to it people just don't have as keen a sense of taste as me. - Zach Braff on I cant believe its not butter",
"I've always preferred Marvel over DC. I just relate to their characters better. I mean look at Wolverine, at first he was just a bit player in an ensemble cast. Now he's the only reason people read X-Men. Just like me and Scrubs. - Zach Braff on comics",
"If you're dumb enough to volunteer for the army, I don't see why we're supposed to feel so bad when you get shot. I'm not saying we should throw a party or anything, but is it such a tragedy? If I'd gotten shot before I made 'Garden State', yeah, that's a tragedy, but some red-state hick getting his legs blown off? Come on. - Zach Braff on the War on Terror",
"It's... it's such a weird thing. After Garden State, so many companies wanted to make my movies, and after The Last Kiss, I realized people would make anything I was in. As long as I keep this up I'll be swimming in chubby indie girl pussy. - Zach Braff on his recent success",
"You know, I've occasionally tried to watch other shows besides Scrubs, but comparing them is a bit like me competing in the special Olympics. Obviously I would win without contest, but the point is that they are trying their best. - Zach Braff on the television industry",
"Sometimes you just gotta use what God gave you to the best of your abilities. - Zach Braff on Prostitution",
"I think the [New England] Patriots' season should have an asterisk next to it because everything they're accomplishing is against teams coached by people other than me. - Zach Braff on the National Football League",
"I like hot dogs. I like eggplant.  I like pizza and creamed corn and beer. But I don't like Arabs. - Zach Braff",
"I don't even like the show that much, I mean, it's about doctors. It's not like doctors are as important as actors anyway, I bet I've saved more lives with my acting talent then any doctor has. - Zach Braff on Scrubs",
"Some people just can't handle that they will never be a better actor than me - Zach Braff on Heath Ledger.",
"Its sad, because he still owes me $20 - Zach Braff on Heath Ledger's Death",
"It turns out Superman is weak to Kryptonite and horses. - Zach Braff on Christoper Reeves",
"Actually, I stopped looking at myself in the mirror years ago. I wasn't making it to work on time. - Zach Braff",
"If Democrats want to start winning elections in this country, they're going to have to start connecting with voters as well as I connect with my fans. - Zach Braff",
"One time I considered making a video game about my life where people control a character called 'Zach Braff' and run around being awesome. Then I realized that getting to pretend to be me would be like shooting up heroin for anyone who played it, and I don't want that on my conscience.  - Zach Braff",
"Christians are like retarded people. They're fun to have around for a good laugh, and easy to fuck if you get them away from their parents, but not someone you want in a position of any authorityor reproducing.  - Zach Braff on religious tolerance",
"You know... as an actor I'd love to pick one up sometime. It would be good for my image, as well as doing lawnwork.  - Zach Braff on Iraqi Orphan Children.",
"Sometimes Sarah [Chalke] starts to talk about Iraq or whatever and she gets all excited, like I actually give a shit what she's saying. Come on, she's a woman. But still, it's very cute. - Zach Braff on politics",
"The way I see it is, if I have a chance to make some kid's dream come true, then yeah, I'm gonna do it. I don't see anything immoral about it. - Zach Braff on sex with underage girls",
"I've always tried to learn from the greats: Orson Welles, Humphrey Bogart, Ghandi, Buddha, Jesus... it's just that there's this tremendous pressure to correct all the things they got wrong. - Zach Braff on role models",
"I didn't really audition for Scrubs. I walked in and they were like yeah, that's perfect and the rest is history. - Zach Braff on auditioning for Scrubs",
"I guess if it turns out he's also gay - Zach Braff on how McGinley's son could amuse him more",
"I lot of people remember when that kid spray-painted my brand new Porsche for Punk'd. That was pretty funny. He got me pretty good. Of course, most people don't know I eventually got him back with my own show. I call it a show, really it's just an hour-long video shot in my bedroom featuring the two of us.   - Zach Braff on the motivation behind Rape'd",
"I don't like the term 'black people', I find it demeaning to those of us that actually qualify as 'people'. - Zach Braff on being politically correct.",
"I really do take more vacations than the president. You can quote me on that. - Zach Braff on vacation",
"People have always wondered what my opinion on Stevie Wonder is. I say if he's so great how come he can't see? I mean, God doesn't make mistakes, just look at me for example. - Zach Braff on Music",
"I've never had much sympathy for orphans, I mean, when I was their age I would have killed to have no parents to make me clean my room and stuff - Zach Braff on orphans",
"Watching John C. McGinley half-ass his lines, probably. Watch Platoon, when he's around Sheen, Dafoe, Berenger. I wouldn't say he's good in it, but you can tell he's trying. It just makes me feel so good to know that I've crushed his work ethic and passion, it's like he knows he'll never be on my level. - Zach Braff on what keeps him going in life",
"For me, it's framed portraits of my erect penis on every wall. - Zach Braff on home decor",
"People need to lay off, I only sell them the coke. I don't tell them what to do with it. - Zach Braff on selling blow to children",
"Sometimes, with friends, I speak in code. For example, instead of the word 'fuck', I say 'Braff.' And, instead of 'bitch', I say 'Zach Braff fan.' And, instead of 'vagina', I call it a 'Braff-hole.' So, if you hear me say 'I Braffed the Zach out of that Braffing Zach Braff fan. Braffed her right in her Braffing Braff-hole', you'll know what I'm really talking about. Oh yeah, instead of 'shit', I say 'Zach.' - Zach Braff",
"I just remember watching them as a kid. You ever laugh so hard that your face muscles cramp? It was like that every time for me. - Zach Braff on snuff films",
"I said, 'I'm on this TV show and I love doing it, but I don't want to be known always as the silly Scrubs guy'. So part of me was like, 'You know what? Life's short. Let's go for it.' - Zach Braff on his entry into drug trafficking",
"Sure, I love my mom. But all she did was sit back and take some genetic material and shot me out 9 months later. It's not like she wrote, directed and acted in Garden State.  - Zach Braff on his mother",
"Not that I'm condoning what he did, but I can probably credit my success to him.  I would have had to compete with a lot more talent if it wasn't for him. - Zach Braff on Adolf Hitler",
"It's not that I'm racist or anything, because I'm not, but I just don't think we should be wasting our time helping people that are going to die soon anyway. - Zach Braff on helping Africa",
"It's not like I could have somebody killed. Well, I could, but I don't have people killed. I mean, I don't as in I'm not having someone killed right now, at this moment, but if anyone fucks with Zach Braff, yeah, they're dead. - Zach Braff on Criticism",
"Hitler had the right idea. He was just an underachiever. - Zach Braff on genocide",
"I really don't understand what the big deal is. You'd think after a couple viewings of Garden State that they wouldn't need all those expensive operations. - Zach Braff on Health Care",
"I actually just call him Turk now, on and off set. I just don't care enough to remember his name. I used to just refer to him as the brown one but that caused too much protest on the set. - Zach Braff on Scrubs co-star Donald Faison",
"You know I was just taking a dump one day, and then as I sat there I realized, I really do deserve better. - Zach Braff on himself",
"I'd never hit a woman unless I was already out of Viagra. - Zach Braff",
"Yea, I had a dream too. Looks like mine came true. - Zach Braff on The MLK Assassination",
"I don't really see the need for it. Why wouldn't everyone just use a mirror like I do? - Zach Braff on pornography",
"I certainly do not consider myself the next Jesus. I'd say he was more of a precursor to Zach Braff. - Zach Braff",
"I'm far bigger than he ever was. I probably have a longer lifespan, too. - Zach Braff on Oscar Wilde",
"I was inspired by World Vision. It's almost like I sponsored (Donald) Faison and gave him an opportunity to do something with his life. What more would he want than to work with me?  - Zach Braff on opportunities",
"All I'm saying is that if it ever becomes a reality, I'd fuck myself. I mean, who wouldn't? - Zach Braff on Cloning",
"You know, in hindsight, I can see why Heath would turn to suicide. I mean...let's be honest, he wasn't me. - Zach Braff on Heath Ledger's death.",
"Looks like someone else beat me to it - Zach Braff on Hitting Sarah Jessica Parker with a shovel in the face",
"I don't belive Oprah's sexual abuse stories, I mean who would take a black girl when there are plenty of white? - Zach Braff",
"People still make New Year's resolutions?  Wow.  I figured those were pointless once I perfected myself by directing, writing, and acting in Garden State.  I guess it makes sense, though.  It gives people a chance to hope that they can become as great as me someday. - Zach Braff on New Year's resolutions",
"I don't know why people were so upset with me. Prince got his own symbol. I just wanted to adopt the handicap symbol as my own so I could park in handicap spots. Deformed people should be honored to park so close to me. Meeting a celebrity like me may give them hope in their mistake of a life. - Zach Braff",
"I'm not 'for it' because I think it's sometimes necessary, I just find them really funny. - Zach Braff on abortions",
"I once looked in the mirror at myself and noticed that, without a doubt, I am a sexy man. In fact, I don't think I'll ever get married...it just wouldn't be fair for my spouse to catch me enjoying a look in the mirror more than having sex with her. - Zach Braff on managing vanity",
"I really don't like doing it, you know? It just feels like the world is losing millions of opportunities for a better quality of life every time I do. I don't want humanity to lose the second most influential director of all time to some sock. - Zach Braff on masturbation",
"I know I can't say this is worse than the Holocaust, but... this  is worse than the Holocaust - Zach Braff on the ABC lineup",
"Not to be rude, but if people are too irresponsible to look after their own, why should I give them mine? - Zach Braff on giving blood",
"They tend to offer the money back. - Zach Braff on hookers",
"Yeah, I guess it's good...but not 'Zach Braff' good. - Zach Braff on Stairway to Heaven",
"Well, I'm not saying that America is a bad place or anything. I just think 9/11 needed to happen sooner or later. - Zach Braff on terrorism",
"People often ask me when there's going to be a Mrs. Zach Braff. It's a confusing question sometimes because many people don't realize that my mother is named Mrs. Zach Braff. - Zach Braff on marriage",
"Bigger than the Beatles? Well, how many grammys did they win? Exactly, none, yet I have one, and I've never even released a CD. - Zach Braff on The Beatles",
"The fact that 'Scrubs' is so popular in Israel is very important to me. I feel like I'm helping to cancel out the thousands of years of oppression the Jewish people have suffered. - Zach Braff",
"If I could change anything about Garden State, it would be to cast somebody else for the female lead. Natalie just isn't really that good of an actress. Especially when compared to me. Just watch the two of us, it's light and dark. I am by far the better Jew.  - Zach Braff on Natalie Portman",
"Lots of people were giving me flak when I made the deal to do the very last season of Scrubs for $350,000 an episode. When really I'm the one that's being cheated, because the writer's strike is keeping me from all the money that I could be making. I need to eat, too. - Zach Braff on his salary",
"In my opinion, one of the biggest drawbacks about Sergio Leone films are the scores composed by Ennio Morricone. If [Leone] were as talented as I am, he would have made mixtapes for his movies instead of letting some schmuck write the soundtracks for him. But then if he were as talented as I am, he'd be Zach Braff. And have his own Grammy. - Zach Braff on directors less talented than he is",
"Yeah, it's a big problem.  I went to Burger King once, and they were all out of beef.  Can you believe that?  I try to bring attention to it, because it's a serious issue and it's the least I can do. - Zach Braff on world hunger",
"People have called me fake, but personally, I don't think I'm fake because I'm so insincere. - Zach Braff",
"My job as an actor has inspired generations of children to become doctors. My job as a writer has opened up the minds of millions. My job as a director has produced masterpieces that will be taught in film school for ages. - Zach Braff on his legacy",
"I'm not opposed to it. I understand that there are a lot of people out there who can't fully comprehend Zach Braff, and need an easier answer. - Zach Braff on organized religion",
"Turning water to wine? I mean c'mon, that's stupid. They should have let me write the bible. - Zach Braff",
"People say that Elvis stole the blacks' music... I think that's bullshit, right? But even if it was true, it's not like they were going anywhere with it, you know? It's like... we've got shit like Ben Folds and Keane now. What do they have? Xzibit? - Zach Braff",
"Rosa Parks didn't call shotgun. - Zach Braff on civil rights",
"I though it was great when she shaved her head in V for Vendetta. It flatters me that my penis made such an impression on her that she would want to make herself look like it. - Zach Braff on Natalie Portman",
"Oh sure, I have a few black people in my family tree. They're probably still hanging there. - Zach Braff on Family Heritage",
"I heard about the Dalai Lama, you know and I thought to myself, why not me? - Zach Braff on Reincarnation",
"Sure, it was terrible and all, but you have to ask yourself: If the whole city was flooded, why couldn't they just swim to safety? - Zach Braff on New Orleans",
"I've been thinking, and they really should make me my own. It makes me sick thinking about all those lazy slobs living paycheck to paycheck getting no punishment, while I, Zach Braff (writer, director, and actor) am being persecuted for making impactful, life-altering films like Garden State - Zach Braff on income tax brackets",
"Probably the most memorable even of my life is when I was born. It really made me who I am. If I die, I hope to go out the same way I came in, but I don't think my mother would be into that. - Zach Braff on Memories.",
"It's not terrible, I guess, but if Ricky Gervais was half as talented as me, maybe the show would actually be funny once in a while.  - Zach Braff on The Office",
"I think there are bound to be obstacles in any path to success. I mean, I'm Jewish, and there's nothing I can do about that. Instead of sitting around and feeling sorry for myself, I got over it and did something with my life. - Zach Braff on motivation",
"I've had to remove all mirrors from my home.  I just can't seem to look at myself without having to buff the bishop, you know? - Zach Braff on autosexuality",
"Some people just don't want to put in the effort. I just show up and say some lines and I'm famous. Anyone living below the poverty line just needs to shape up or be shipped out, you know? - Zach Braff on effort",
"When I was little I always wanted to drive a train. That, and become a baker. - Zach Braff on the Holocaust",
"I experimented in College like most kids. - Zach Braff on rape",
"I know that [Mike] Tyson talked about wanting to eat his opponent's children, but I don't think he ever had the balls to do it. I'm different - when I kidnapped Bill Lawrence's daughter, I cut off all of her fingers before sending my demands so that I wouldn't have to sit there and wait for him to ignore them. We worked things about about nine hours in, which is good because I ate her thumb as a midnight snack. - Zach Braff on his contract negotiations for the sixth season of Scrubs",
"Cunt. - Zach Braff on his favorite nickname for Scrubs co-star Sarah Chalke",
"There is one person I can think of better than me. And that's Zach Braff. What a cool guy. - Zach Braff on Scrubs as John Dorian",
"Bob Marley, The Grateful Dead, Queen, Janis Joplin, Buddy Holly, Lynyrd Skynyrd, Zach Braff. What do they all have in common? Not a damned thing. Those assholes never won a Grammy. - Zach Braff on winning the Grammy for Best Soundtrack Album",
"I wouldn't call myself a modern Shakespeare, but Shakespeare was probably to his generation what I am to mine. - Zach Braff",
"Sure my penis cures cancer . . . but I don't screw bald chicks - Zach Braff",
"I think we have to acknowledge that people are different and succeed at different things, first of all. Men are better than women at some professions like firefighting, construction work, and physics. But women are better than men at some professions, too, like elementary teaching, prostitution, and giving birth. Who's to say which is more important? - Zach Braff on gender equality",
"I don't do interviews anymore. I mean, any asshole with a pen and paper can write down what I say, but only someone like Hemingway can understand what I'm really saying, you know? - Zach Braff on inteviews",
"The worst part about it is they'll never see one of my movies again - Zach Braff on Chris Benoit",
"When you win your first Grammy, it's true, you really want to thank all the little people. - Zach Braff on Jesus",
"The whole thing did make me feel pretty bad. To cheer up her family I sent them Hungry Hungry Hippos. - Zach Braff on Terri Schiavo",
"I'm not saying that I could have done it better, but I definitely could have been faster. - Zach Braff on Pol Pot",
"It raises several serious questions. For example, how can there possibly be more than one person as awesome as me? - Zach Braff on the ethics of human cloning",
"Well he was originally going to be up against me, but they decided that it wasn't good television for me to be winning every time. - Zach Braff on Bear Grylls and Man vs. Wild",
"Sometimes I regret not being Catholic. I think I'd make a pretty good saint. - Zach Braff",
"My dog has a cough. If you've never seen a dog with a cough, I recommend trying to find one. It's hilarious. - Zach Braff",
"I think they're bogus, honestly. How utter garbage like Crash and Million Dollar Baby can win best picture, where true works of art such as Garden State go untouched is beyond me. It just proves how close-minded America really is, and I refuse to take part in it. - Zach Braff on the Academy Awards",
"I mean, look he may be sexy. He may be able to unleash the dragon but has he ever directed a movie? No. Has he ever been the star of a hit TV series? No. He's great but he's not ZACH BRAFF great. - Zach Braff on Rex Grossman",
"It depresses me when people expect me to be like the characters I play on film. I'm not some whiny loser punk, I'm a man's man. - Zach Braff on himself",
"My co-stars aren't bad actors, but they're no Zach Braff. - Zach Braff on Scrubs",
"He was brilliant in that one show...but EVEN better in Garden State. - Zach Braff on Zach Braff",
"I know I shouldn't blame myself, but I can't help thinking that it's somehow my fault.  I mean, I know how hard it must be for some actors to work in my shadow all their lives.  And I did buy him the pills. - Zach Braff on Heath Ledger",
"I mean, who can blame him? I love the idea. He's an innovator. - Zach Braff on polygamy",
"So for front-runners we have a black and a woman. It's like being made to choose between syphilis or having and old man shit on your face. I would do the country a favor and run myself but I couldn't deprive Hollywood of me for 4 years. - Zach Braff on Presidential candidates",
"The only real difference between hookers, stippers, sluts and regualar women how many times you can hit them before they cry. Hookers can really take a punch, I'll tell you that much.  - Zach Braff on women",
"When you're the director and the writer, you never have to remember your lines, and there's no one to call you on it. On Garden State I did different lines on every take, just making shit up. And it was great each time. - Zach Braff on acting, writing, and directing",
"Yea, I've got a dream too.  It involves time-travel and a rifle. - Zach Braff on Martin Luther King Jr.",
"The best part of being famous is being able to make people's lives a little better just by mine and theirs intersecting. For example, I love having sex with married women because, hey, they get to have sex with Zach Braff. But then when their husbands inevitably catch me doubling their wives' twats with my enormous cock, the husbands get the pleasure of knowing their dick has been the same place as Zach Braff's. And if they're really lucky, they'll raise or find out they're raising one of my bastard offspring. Sometimes serving others is its own reward, you know?  - Zach Braff on selflessness",
"I can't watch the news anymore. They have their priorities all out of whack. All I see is Natalee Holloway and Britney Spears and the war in Iraq. Where's the substantive news? Where's the Zach Braff coverage? - Zach Braff on the media",
"I definitely try to play a common man in my roles so people can identify with my characters, but the truth of the matter is that it doesn't really matter what I do or my lines are, I'm still Zach Braff, and people know I'm better than them. - Zach Braff on being a spokesperson for his generation",
"They say that guys who like chick flicks tend to do a little better with the ladies. Well, I INVENTED the chick flick, so you can pretty much guess where that leaves me. - Zach Braff on the ladies",
"Every year he brings presents to all the kids everywhere, which are worth like millions of dollars, but I get to entertain millions of people and you can't put a price on that. - Zach Braff on Santa Claus",
"I mean, I know I'm not as famous as him but, in a few years I'll bet that I'll be getting just as much praise as him. - Zach Braff on God",
"In April 1975 I was born and the Vietnam War ended. I could not let any American die in war before seeing an episode of Scrubs. - Zach Braff on his impact on US Foreign Policy",
"I actually did ponder doing the Brad Pitt/Angelina Jolie thing and get a kid from Ethiopia.  But you know, I already have an ashtray. - Zach Braff on adoption",
"Rain Man makes me laugh - Zach Braff on autism",
"If we've learned anything, it's that the combination of yellow smiley faces and blue polyester vests are irresistible to the inbred. - Zach Braff on Wal-Mart",
"Ha ha yeah. That was hilarious. Did you see those people jumping? Ha! Did they really think they could actually survive that fall? I guess Darwin was right - Zach Braff on 9/11",
"I feel kind of bad for them, really. I mean, all they want is to live in the same country as Zach Braff.  - Zach Braff on illegal immigration",
"By then I realized, fuck I'm Zack Braff, I shouldn't have to wipe my own ass - Zach Braff on hiring a maid",
"My favorite meal? It has to be furburgers everyday in the morning. - Zach Braff on breakfast",
"I always liked the story of Noah's Ark and the idea of starting anew by rescuing the things you like and leaving the rest behind. - Zach Braff",
"A lot of people say colonialism was 'evil' or whatever, but what have they really done with Africa since we gave it back to them? I don't think it should be considered 'racist' to admit maybe ending apartheid did more harm than good in South Africa. - Zach Braff",
"Wait, was the horse ok? - Zach Braff on Christopher Reeves",
"It's just like when me and my friends hang out. Well, if I was a no talent hack and my friends were menopausal idiots. - Zach Braff on Seinfeld",
"It's something to do - Zach Braff on rape",
"Women are like parking spots, the best ones are handicapped. - Zach Braff on dating & relationships",
"He just said what everyone was thinking - Zach Braff on Michael Richards",
"No one can ever accuse me of being selfish. Every year I collect my sperm in a milk jug and then I add it to the city's drinking water. Anyone that drinks water on January 1st in the Los Angeles area has gotten a personal gift from me for the past 4 years. - Zach Braff on generosity",
"When I let some girl take me in her mouth I think this is what Jesus must feel like during communion. - Zach Braff on religion",
"I mean, just get a freaking job already - Zach Braff on the homeless",
"It's not like I'm a pyro or anything, I just think burning them saves a lot of space - Zach Braff on the jews",
"Well, if they're going to do it, there'd at least better be a screening of Garden State on the way up. Nobody, living or dead, should be denied my presence. - Zach Braff on abortion",
"At first, I didn't really care if global warming existed. But then I realized it means that less bums would freeze to death in the winter - Zach Braff on Global warming",
"I just don't see how anyone can hate America. I mean, shit, I live there. What more do you need? - Zach Braff on terrorism",
"The Jews are just clumsy bakers. - Zach Braff on the real explanation for the Holocaust",
"One time this guy on the street wanted me to give him a medical opinion, because I'm a doctor on TV. I'm also a real doctor. But I'm also Zack Braff, so I kicked him in the groin. - Zach Braff",
"The problem with doing commercials is that the only thing good enough for me to sell is myself, and I stopped doing that once I kicked my coke habit. - Zach Braff on advertisements",
"Hitler was about population control. - Zach Braff on Adolf Hitler",
"I actually don't have a big problem getting decent chicks. I'm charming, and know some slick moves. If you like a cashier in a gas station, buy a lottery ticket. When she asks what kind, say Pick your favorite one. She goes to hand you the ticket you tell her Keep it. Maybe you'll get lucky. Then leave. Talk right, and you can get that chick.  - Zach Braff on his love life.",
"I think the car crash happened at about the right time. Before she died, the worldwide press were very much entirely focussed on her, but after she died, it paved the way for me to take center stage in the media. - Zach Braff on Princess Diana",
"I find it hard to believe that so many people doubt the existence of God.  I mean, seriously, I'm here, so is it such a stretch to imagine that another all-powerful being could exist somewhere in the universe? - Zach Braff on God",
"Shortly after writing, directing, and starring in Garden Sate. I was driving and I was crossing an intersection. Just as soon as I had passed it, the man in the car behind me was hit and killed by someone running the red light. I thought to myself, Man just a few seconds earlier and that would have been me. But then I figured that God decided to kill that nobody in the car behind me, and spare my life because I would do, and had already done a greater service to the world, just being me. - Zach Braff on his fame",
"I don't know why everyone is making such a fuss. I'm still here. - Zach Braff on The war",
"I'm sick of people saying I hate blacks, women, and gays. It's false and slanderous. Everyone who knows me knows I hate the Chinese. - Zach Braff",
"I never go easy on kids when I play board games.  The sooner they learn what the consequence of entering a competition is, the better.  If they win, I punch them in the face like any adult. - Zach Braff on board games.",
"You want to know the secret of my success? Let me tell you about eugenics... - Zach Braff on selective breeding",
"I'm not saying that they're all delicious, but they're worth a try. - Zach Braff on endangered species",
"Prohibition didn't work, so why should emancipation work?  I think we should just stick with a system that has proven to be effective. - Zach Braff on slavery",
"They kept telling me to catch all of them.  I got my first one for free and named it ZACHBRAFF.  I'm pretty sure that's all anyone could ever need. - Zach Braff on Pokemon",
"At this point I feel like I could go out and accomplish anything.  I'd just love to see Will Smith's face if he found out I, Z-Braff, have the number one rap album in the country.  That'd show that no-talent uncle tom. - Zach Braff on ambition",
"It'll tell the life story of genius who overcame insurmountable odds, which inspires millions to believe that they too can achieve their dreams. - Zach Braff on his next film titled Zach Braff",
"When I think about the holidays, I think about the Salvation Army guys ringing bells in front of stores. They're always so nice to you and they're always willing to give a heart to heart conversation. They actually bear the winter cold to ask for your petty cash with a smile on their face. Fuck those guys. - Zach Braff on Christmas charity",
"I helped Sarah Chalke invent the phrase bend over backwards, it was a fun night - Zach Braff on sodomy",
"Look, you are misunderstanding me.  All I'm saying is, if they can eat my dog, why can't I eat them? - Zach Braff on Koreans",
"Well I don't like to think too far ahead because it scares me a little to think of what this world will come to after I'm gone, but I suppose life will have to go on, right? At least everyone will still be able to watch reruns of Scrubs. - Zach Braff on the future",
"It's about a young heart surgeon that returns to his hometown and finds romance. I would describe it as a kind of cross between 'Garden State' and 'Scrubs.' - Zach Braff on his new film Open Hearts",
"Let's face it, it's only called Scrubs because I'm saving 'Zach Braff' for my autobiography. - Zach Braff on Scrubs",
"A wave did knock me down once when I was at the beach so I can kind of relate. - Zach Braff on the 2004 tsunami",
"You know, I think there should be a Zach Braff Day. We could have it on December 25th and then people can decide whether they want to celebrate me or Jesus. If you ask me, the choice is pretty obvious.  - Zach Braff on Zach Braff Day",
"Look on the bright side; that's one bullet that's not going to hit me.  - Zach Braff on the assasination of Benazir Bhutto",
"I mean just shut up and eat something already and get some real clothes. Honestly, who's going to respect a man wrapped in a sheet? How can you take him seriously? Contact lenses wouldn't kill ya either - Zach Braff on Mahatma Gandhi",
"What's that? Did I? What do you think? - Zach Braff on Natalie Portman",
"I punched Robin Williams. - Zach Braff on memories",
"The greatest charity you can contribute to is yourself. Instead of spending a dollar to help feed hungry children, why not spend that dollar on hair gel so you can get the perfect cowlick? - Zach Braff on self-improvement",
"It's kind of ironic that my character is a doctor who acts very gay with his best friend. I don't see how gays could ever be doctors, they spend too much time whining about everything. Just get off your soapbox and go back to designing floral arrangements - Zach Braff on gay marriage",
"I mean, nobody's ever thrown a big rock at me or my friends, but we're all pretty tough guys and could probably handle it. - Zach Braff on dinosaur extinction",
"I've heard they're pretty fast  - Zach Braff on Obama running for President",
"I still don't see how they fit them in the balls. Animals plus small, compact spaces equals angry people. Just ask my friend, Michael Vick. - Zach Braff on Pokemon",
"Sometimes, when I wake up in the morning, I look in the mirror, and then look outside. I get a hard-on while thinking that no one else in the world gets to see my reflection in their mirror unless they bought a special mirror. I then watch myself jerk-off in the mirror, and come when I think about how I'm going to sue those assholes with my reflection in their mirror for appropriating my image without my consent. I take the load I just shot, put it in a jar, and sell it to Sarah Chalke for a couple of grand because it is what keeps her nappy ass head looking half decent. - Zach Braff on Morning Routines",
"Okay, he can talk white, he can act white, but when it is all said and done, he's going to make lynching illegal. And I can't stand for that. - Zach Braff on Barack Obama",
"It's great to be white. - Zach Braff on racial tolerance.",
"I mean, they just don't make them big enough. Not that i would use one anyway. - Zach Braff on condoms",
"I personally love the little guys, and they really know to get the job done. - Zach Braff on illegal immigrants",
"It's a give and take relationship with my fans. They give me love and adoration, and I take it from them. - Zach Braff on fans",
"It's just people trying to get on TV, not like it's really going to do them any good since people can just watch me. - Zach Braff on Public Access Television",
"When I played the Shins, I changed someone's life. When I play Belle and Sebastian in a pivotal scene in my next movie...well, let's just say I made sure I that I can't be held legally responsible for all the deaths people will suffer out of shock upon hearing them. They're a terrific band. - Zach Braff",
"I'm not saying I hate Jews, I'm just saying that I think they shouldn't be alive any more. - Zach Braff on Jews.",
"I didn't forget about the people that made me famous, you know? I still remember them and all and they did a lot for me. It's just that they don't have very much money so they, like, aren't that important to me anymore. - Zach Braff on fans",
"I don't see what the big deal is, he had millions of Jews under his control and what did he do? Go swimming and wander the desert? I would've started a law firm, so he's kind of an idiot. - Zach Braff on Moses",
"What an asshole, he didn't even show up to the premiere of his own movie. - Zach Braff on Heath Ledger",
"It just doesn't seem that extreme to me.   - Zach Braff on Chris Benoit's parenting skills",
"At first I thought they were prostitutes hired by the producers to have some fun with in between scenes - Zach Braff on Sarah Chalke and Judy Reyes",
"I mean if it's half mine, I can make half the decision.  So let's just do it halfway and see what happens from there. - Zach Braff on abortions",
"I'm really not one to brag, but I think my job is one of the most important things someone can do with their life. I mean, it really gives people a chance to live outside their means through someone else's vision. And I think that's something really great that I can give back to the community. Sure I could be a doctor or a lawyer, but do they really help anyone? Sure you can save someone's life, but can you really change it for the better? I'm not saying their jobs aren't important, just not as important as mine. - Zach Braff on Jobs",
"I'm by no means condemning prescription medicine for mental health. I've seen it save a lot of people's lives. But for all of its faults, Scientology is dead on where it comes to modern psychiatry.  - Zach Braff on psychiatry",
"Everybody makes a big deal out of it, but I don't really see the point.  Sure, they can crunch numbers, but I've got a bunch of Asian kids or whatever in my garage that do the same thing.  It's not like it's anything new. - Zach Braff on computer science",
"When life handed me lemons, I made Scrubs - Zach Braff on his co-stars",
"Somebody approached me about writing a biography on me, I told them they were too late. - Zach Braff on the bible",
"Kids used to say, 'how much wood could a woodchuck chuck if a woodchuck could chuck wood?'. Nowadays the kids all say, 'How much Zach Braffs could a Zach Braff Braff if a Zach Braff could Scrubs Garden State. It's a little easier for the little bastards. - Zach Braff on tongue twisters",
"He may be an Oscar nominee, but that doesn't change how fucking short he is. - Zach Braff on his costar Ian Holm",
"I like to see them as my personal food supply if the slaves go on strike - Zach Braff on Fat People",
"These people should be made to clean the streets - they drop their crap everywhere. - Zach Braff on Lepers",
"I showed up to the club and he wasn't there. Pussy. - Zach Braff on 50 Cent",
"I don't see the big deal. It's going to come out sooner or later. I figure if it comes out sooner, it'll take up less room in the compost heaps. - Zach Braff on abortion",
"Not once did I ever actually write a report in college. Instead, I would just masterbate onto a copy of the book and turn it in. Not only did I get A+'s, i got my doctorate in just 6 months. - Zach Braff on term papers",
"When things seem to be slowing down, there's this little trick I like to play. I'd plow this virgin who's on her period, and after I'm done I'd just run out into the living room, or the dance floor, with all that bloody goop on my junk and yell, OH MY GOD, I'VE BEEN SHOT IN THE NADS! Yeah, good times. - Zach Braff on entertaining at parties",
"Talentless hacks.  It looked exactly like when I ejaculate.  Try something original next time. - Zach Braff on the Challenger explosion",
"She can't say no if she's unconscious. - Zach Braff on consensual sex.",
"I only really leave it on if I see myself, because, come on, is it really worth the time otherwise? - Zach Braff on TV",
"If we're going to solve the problems in North Korea, the first thing we're going to have to do is start helping them get basic amenities like electricity, televisions, and DVD players over there. Otherwise, how can they watch 'Garden State'? - Zach Braff",
"The funny thing about women is that they honestly seem to believe their opinions matter to other peopleand by 'people' I of course mean 'men'. You know, actual human beings. - Zach Braff on feminism",
"If I had a billion dollars I would...oh wait...already do. - Zach Braff on world hunger",
"I couldn't use the bathroom without them. - Zach Braff on hundred dollar bills",
"My nose is way bigger than his is, where's my cereal brand? - Zach Braff on Toucan Sam",
"It's all about being a part of something in the community, socializing with people who share interests and coming together to help improve the world we live in. - Zach Braff on the KKK",
"It's funny when I read the tabloids and they're reporting on only a fraction of the life I'm leading. - Zach Braff",
"I can't see why white people can't use that word. I have lots of black friends. That automatically proves I am not a rascist. - Zach Braff on the N-word",
"Well, you need to have at least one black friend, otherwise people think you're racist - Zach Braff on why he's friends with Donald Faison",
"I prefer to think of it as masturbating with someone else's mouth. - Zach Braff on blowjobs",
"Michael Eisner contacted me once and asked me if he could change the name of Disneyland to 'Braffland.' I said no, because whenever I go to Disneyland there's always fat people everywhere wearing tight clothes. Disneyland, frankly, has a lot of improving to do before it gets my namesake. - Zach Braff on achievements",
"I tried it a few times but didn't see the point. I'm Zach Braff. What the fuck do I need a team for besides holding me back and sucking? If I wanted that, I'd just walk on the set of 'Scrubs'. - Zach Braff on Team Fortress 2",
"When I first moved to L.A., I thought about turning gay. Then I realized none of the guys I was interested in was good enough for me. - Zach Braff on sexuality",
"I was bullied in school by a guy called steve, he was real mean. So i had him killed, so whos laughing now....not him, he's dead - Zach Braff on Dog rearing",
"I'm grown ass man and grown ass men can do whatever they want, got it? - Zach Braff on child pornography",
"Well once I found out how old they really were, I stopped hitting on them altogether - Zach Braff on understanding dog years",
"I'm always being told by directors that I add chemistry to scenes, so I mean how difficult could it be? - Zach Braff on nuclear fission",
"I guess it kinda tastes like egg or squid. You gotta make sure they're cooked properly or they taste like a piece of rubber covered in corn syrup. - Zach Braff on fetuses",
"I turned down the role that DiCaprio had in Titanic, in retrospect it was still a great decision, audiences would never believe a physical specimen like myself couldn't just swim to shore. - Zach Braff on casting",
"Money can't buy you happiness; but it can buy you hookers, guns to kill the inferior races AND porn - which is kinda the same thing. - Zach Braff on Money",
"I can't say I agree with something that takes the focus away from me. - Zach Braff on Religion",
"I could be one if I wanted to, I'm just way too overqualified for a job that simple. - Zach Braff on Presidents",
"Zach Braff, Zach Braff, and hmm... Let me think about it for a minute. Umm... Zach Braff.  - Zach Braff on who were his top 3 favorite people.",
"People are always going to find fault with anything you do, any process that you're a part of. The creative process means taking risks, I've taken risks and I've made mistakes, but the bottom line is, could anyone else have done any better ? I have to believe that what I created was worthwhile. - Zach Braff on Intelligent Design",
"It's not that George Bush doesn't care about black people, god made hurricanes, not people who can't swim. - Zach Braff on racial stereotypes and how they affect everyday life",
"I was excited about The Dark Knight until Heath Ledger gave away the ending, Batman always wins. - Zach Braff on movie spoilers",
"When you were a kid and the circus came to town it was awesome to see these little creatures, but these things go out of fashion, like polyester blazers with rolled up sleeves. We don't have to suffer them anymore so why are there all these little people running around? - Zach Braff on Midgets/Dwarves",
"Luckily there is AIDS - Zach Braff on the growing numbers of homosexuals",
"I mean, so what if it's a little dangerous? A one-armed kid is comedy gold. - Zach Braff on child labor",
"Someone once told me dwarfism is a sexually transmitted disease. Years later I found out they were just joking, but to this day I'm afraid to have sex with anyone under five feet tall unless I'm sure they're children. - Zach Braff",
"I like to think it's Stairway to Heaven - Zach Braff on the zig-zag on his left thigh",
"Have I ever had sex with a hooker? I'd like to answer that question with a question of my own.  Can just anyone look up police records? - Zach Braff on his sex life",
"I was originally casted to be in the Superman movie but I read the script and realized that it was mysteriously similar to my screenplay for Zach Braff the Movie. - Zach Braff on Superman",
"I know I probably should be sad about my mother's cancer... but she still hasn't seen The Last Kiss, you know? - Zach Braff on family",
"They were originally going to call it the Braff, and inside every box it'd just be an autograph with some of my hair. It turns out kids didn't really like it, but kids are idiots and that's why they're in schools. - Zach Braff on the Nintendo Wii",
"If I wasn't an actor? Hmm, I'd probably be a serial killer. I'm just so damn likeable, no one would ever suspect me. - Zach Braff on careers",
"Of course I don't use my A-material, it doesn't matter if they think I'm funny or not because they won't be thinking anything pretty soon anyways, if you caych my drift. - Zach Braff on performing for terminally sick children",
"I could've made a much funnier Joker than him, I just don't like to wear make-up like a sissy boy - Zach Braff on Heath Ledger",
"I'm not lazy, I drive everywhere myself, the bitch could've learned something from me. - Zach Braff on Princess Diana",
"I was approached and asked if they could make a video game based on Scrubs. I screamed, 'Nobody plays Zach Braff, but Zach motherfucking Braff!' and then I punched that little girl in her throat. - Zach Braff on crushing dreams",
"You don't need an alarm clock when you sleep with 20 models a night, one of those broads'll figure out that they better make breakfast in bed or I'll kill all of them. - Zach Braff on relationships",
"I blame Walt Disney; well he has to find voice actors better than me somehow doesn't he? - Zach Braff on Child Abductions",
"Sorry, I can't hear you over the sound of HOW AWESOME I AM - Zach Braff on Zach Braff",
"They're people just like me, except with less money, a lot less money. - Zach Braff on poor people",
"I don't ask questions. I just figure the extra warm days are God's way of rewarding me for Garden State - Zach Braff on Global Warming",
"I am a top contributor to www.ZachBraffQuotes.com. - Zach Braff on www.ZachBraffQuotes.com",
"It took off like United Flight 93. - Zach Braff on Heath Ledger's career",
"I went back a little further than I wanted to and upon arriving I met this schmuck wearing sandals and a robe.  He introduced himself and I said, Jesus?  That's a stupid fucking name.  Try Zach Braff. - Zach Braff on time travel",
"What's happening to them is terrible, but if you think about it, the victims should take some of the blame, really. How hard is it to just jump on a plane and head to the nearest civilized country? And there they can buy the soundtrack to my masterpiece Garden State. It drops this August. - Zach Braff on the Darfur genocide",
"I wouldn't exactly call it 'Intelligent', but somebody has to be behind designing the human form other than just biological necessity. Why else would women have arms? Or feet? Or mouths? - Zach Braff on evolution",
"*Sigh* Back in the good old days they never used to scream. - Zach Braff on Rape",
"It's a real shame they didn't run fast enough, they missed Garden State. - Zach Braff on Columbine Victims",
"I know he made some mistakes but come on ... everyone of us would have done the same in his situation! - Zach Braff on Hitler",
"I never looked at bread the same way again - Zach Braff on yeast infections",
"They're like slinkies really; absolutely pointless but hilarious to watch one fall down some stairs. - Zach Braff on the physically disabled",
"One of the things I like about being a celebrity is that you can get away with murder. Not just metaphorically, literally. Remember that annoying blond bitch reporter at E News used to talk smack about me? I paid two mobsters five million dollars each to throw her off the Stratosphere tower in Las Vegas. - Zach Braff on Fame",
"Honestly, I had no idea that the whole process had already been perfected over the past 100 years, I'd never heard of Muybridge, or Edison, zoetropes or kinetiscopes, optical tracks, ... I mean, I just came up with this idea to imprint images on moving strips of cellulose impregnated with photosensitive chemicals and then process those strips and repeat those images with a light shining through it, accompanied by recorded sound, which I also came up with that morning. I mean, shit, I coulda saved SO much time that day ! *laughs* - Zach Braff on his directorial debut, Garden State",
"I believe the general consensus is the bigger it is, the more women flock to you. I guess its a good thing mine is HUGE! - Zach Braff on bank accounts",
"That cyclone in Burma? That was just me doing the dance to that annoying ass song... - Zach Braff on Burma",
"I think the Bible should be re-written for today's society.  We can call it 'Scrubs.' - Zach Braff on the Bible.",
"Well I can understand why men want it to be legal. Obviously they're all hoping they might get to marry me someday. I hate to burst their bubble, but they should just give it up now. Zach Braff doesn't sway that way, you know? - Zach Braff on gay marriage",
"They choreographed the whole thing and I wasn't supposed to catch the kid, but I caught him... and I'm not a big fighter or anything, but, with the adrenaline and everything, I just started pummeling him. I didn't know and it was so dark...but part of the punking was that it was, like, a 12-year-old. It turns out it was fake spray paint. They edited the fight out, because apparently you're not supposed to punch people on Punk'd. - Zach Braff on disciplining children",
"I was stuck in an elevator with a bunch of people once, so I really don't see what the big deal is. - Zach Braff on Anne Frank",
"People ask me, 'Did the fame come too fast? Do you ever wish for your old life?' I always tell them that there's nothing on earth better than being famous. - Zach Braff on his roots",
"It's called Craigslist because I hate the name Craig, and those are the only people I haven't slept with. Thus, that's why they're so desperate. - Zach Braff on Craigslist",
"The question is, Do I have a 'God Complex'? Which makes me wonder if this douchebag has any idea as to the kind of talent one has to demonstrate to be accepted as an actor in Hollywood. Or if you have the vaguest clue as to how talented someone has be to direct an acclaimed motion picture. And don't forget that I have an M.D. from Harvard. I am board certified in cardiothoracic medicine and trauma surgery. I have been awarded citations from seven different medical boards in New England; and I am never, ever sick at sea. So I ask you, when someone goes into that chapel and they fall on their knees and they pray to God that their wife doesn't miscarry, or that their daughter doesn't bleed to death, or that their mother doesn't suffer acute neural trauma from postoperative shock, who do you think they're praying to? Now, you go ahead and read your Bible, Dennis, and you go to your church and with any luck you might win the annual raffle. But if you're looking for God, he was in operating room number two on November 17th, and he doesn't like to be second guessed. You ask me if I have a God complex? I AM GOD. - Zach Braff on being God")
length = len(quotes)


class ZachBraffQuotes(callbacks.Plugin):
    """
    Prints random quotes extracted from zachbraffquotes.com
    """
    
    def zbq(self, irc, msg, args):
        irc.reply(quotes[randint(0,length)])


Class = ZachBraffQuotes
